server {
  listen 443 ssl http2;
  server_name <REDACTED-DOMAIN>.de;

  # wildcard certificate
  ssl_certificate      /etc/nginx/ssl/<REDACTED-DOMAIN>.crt;
  ssl_certificate_key  /etc/nginx/ssl/<REDACTED-DOMAIN>.key;

  location / {
    # reverse proxy to nodeapp on local port 12000
    proxy_pass http://127.0.0.1:12000;

    # set headers to also allow websocket upgrade path
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
